# Generated by Django 4.0.5 on 2022-06-15 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('question', models.CharField(max_length=500)),
                ('solution', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('createt_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('createt_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('example', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equation.example')),
            ],
        ),
    ]
