# Generated by Django 4.0.5 on 2022-06-15 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equation',
            name='example',
        ),
        migrations.AddField(
            model_name='example',
            name='equation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equation.equation'),
        ),
    ]
